### ISSUE TITLE
Some Facebook/Twitter links lead to incorrect profiles

### ISSUE THREAD

**Issue by curtismatthias** [coverless/peopole#4]

**Comment by swcraig** [comment]
Added a lil' something to the judge.

run $> ruby judge.rb -ignore "Name of Person" profile_type
i.e   $> ruby judge.rb -ignore "Frank Ocean" twitter

This will overwrite the entry for Frank Ocean's twitter account so that it won't show on the site anymore. One thing to note, if this would cause a person to now have all three facebook, twitter, and wikipedia information blank, the judge will attempt to repopulate all three the next time it is run.  I think everyone will have at least a wikipedia page so it should be alright.
